---
title: "World Bank Python Analysis Python"
author: "Yashvi Malviya"
date: "`r Sys.Date()`"
output: html_document
urlcolor: "blue"
params:
  solutions: TRUE

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo       = params$solutions, 
                      eval       = params$solutions,
                      fig.align  = "center",
                      fig.height = 3, 
                      fig.width  = 5)
```

# World Bank Data

The World Bank is an international organization that
provides loans to countries with the goal of reducing poverty. The 
data frames in the dt folder were all taken from the public data 
repositories of the World Bank.

- country.csv: 
  Contains information on the countries in the data set. The
  variables are:
    - `Country_Code`: A three-letter code for the country. Note that not all
      rows are countries; some are regions.
    - `Region`: The region of the country.
    - `IncomeGroup`: Either `"High income"`, `"Upper middle income"`, 
      `"Lower middle income"`, or `"Low income"`.
    - `TableName`: The full name of the country.
- fertility.csv: 
  Contains the fertility rate information for each country
  for each year. For the variables `1960` to `2017`, the values in the cells
  represent the fertility rate in total births per woman for the that year. 
  Total fertility rate represents the number of children 
  that would be born to a woman if she were to live to the end of her 
  childbearing years and bear children in accordance with age-specific 
  fertility rates of the specified year.
- life_exp.csv: 
  Contains the life expectancy information for each country 
  for each year. For the variables `1960` to `2017`, the values in the cells
  represent life expectancy at birth in years for the given year. 
  Life expectancy at birth indicates the number of years a newborn 
  infant would live if prevailing patterns of mortality at the time of its
  birth were to stay the same throughout its life.
- population.csv: 
  Contains the population information for each country. For
  the variables `1960` to `2017`, the values in the cells represent the total
  population in number of people for the given year. 
  Total population is based on the de facto definition of
  population, which counts all residents regardless of legal status or 
  citizenship. The values shown are midyear estimates.
  
1. Use relative paths to load these data frames into Python.

```{python}

destination_directory = r"C:\Users\nishi\OneDrive\Desktop\Github projects\python"
current_directory = os.getcwd()
print("Current Working Directory:", current_directory)
os.chdir(destination_directory)
new_current_directory = os.getcwd()
print("New Current Working Directory:", new_current_directory)

```

```{python}
import pandas as pd

dt_folder_path = os.path.join(destination_directory, '..', 'dt')

files = ['country.csv', 'fertility.csv', 'life_exp.csv', 'population.csv']

file_paths = [os.path.join(dt_folder_path, file) for file in files]

country, fert, life, pop = [pd.read_csv(file_path) for file_path in file_paths]


print("Country Data:")
print(country.head())
```
    
2. (2 pts) These data are messy. The observational units in `fert`, `life`, and `pop`
   are locations in space-time (e.g. Aruba in 2017). Recall that tidy data
   should have one observational unit per row. Make these data tidy now.
   
```{python}

def make_tidy(df, var_name):
    df_tidy = pd.melt(
        df,
        id_vars=['Country Name', 'Country Code'],
        var_name='Year',
        value_name=var_name
    )
    return df_tidy


pop_tidy = make_tidy(pop, 'Population')

print(pop_tidy.head())

life_tidy = make_tidy(life, 'Life Expectancy')

print(life_tidy.head())

fert_tidy = make_tidy(fert, 'Fertility')

print(fert_tidy)
```
    
3.  Combine these data frames so that we have the fertility rate, population,
   life expectancy, and the region for each country in each year in a single
   data frame. The resulting data frame should look like this
   
```{python}
import pandas as pd
import numpy as np


merged_df = fert_tidy.merge(life_tidy, how='outer', on=['Country Name', 'Country Code', 'Year'])
merged_df = merged_df.merge(pop_tidy, how='outer', on=['Country Name', 'Country Code', 'Year'])


wb_df = merged_df.merge(country, how='left', left_on='Country Code', right_on='Country Code')


wb_df = wb_df.rename(columns={'Fertility': 'fert_rate', 'Life Expectancy': 'life_exp', 'Population': 'population'})


wb_df = wb_df[['Country Name', 'Country Code', 'Year', 'fert_rate', 'life_exp', 'population', 'Region']]

wb_df.head()
wb_df.info()

```
    
4.  Make a scatterplot of fertility rate vs life expectancy, color-coding by region. Do this for the years 1960, 1970, 1980, 1990, 2000, and 2010. Facet by these years. Make your plot aesthetically pleasing.  Your final plot should look like this:

```{python}
import seaborn as sns
import matplotlib.pyplot as plt

selected_years = ['1960', '1970', '1980', '1990', '2000', '2010']
filtered_data = wb_df[wb_df['Year'].isin(selected_years)]
sns.set(style="whitegrid")
g= sns.FacetGrid(filtered_data, col="Year", hue="Region", col_wrap=3, height=2, aspect=0.80)
g.map(sns.scatterplot, "life_exp", "fert_rate", alpha=0.7, edgecolor="w", s=100)
g.add_legend()


plt.show()

```
    
5.  Calculate the total population for each region for each year. Exclude 2018. 
   Make a line plot of year versus total population, color-coding by region.
   Your final plot should look like this:
   
```{python}
import matplotlib.pyplot as plt
import seaborn as sns

selected_years = ['1960', '1970', '1980', '1990', '2000', '2010']
filtered_data = wb_df[wb_df['Year'].isin(selected_years)]

total_population = filtered_data.groupby(['Year', 'Region'])['population'].sum().reset_index()


sns.set(style="whitegrid")
plt.figure(figsize=(8, 6)) 
sns.lineplot(x='Year', y='population', hue='Region', data=total_population, marker='o', palette='muted')

plt.xlabel('Year')
plt.ylabel('Total Population')
plt.title('Total Population by Region Over the Years')


plt.legend(title='Region', bbox_to_anchor=(0.99, 1), loc='upper left')

plt.show()


```
    
6. Make a bar plot of population vs region for the year 2017. Your final  plot should look like this:
```{python}
import matplotlib.pyplot as plt
import seaborn as sns


data_2017 = wb_df[wb_df['Year'] == '2017']

fig, ax = plt.subplots(figsize=(10, 7))

sns.set(style="whitegrid")
sns.barplot(x='Region', y='population', data=data_2017, ci=None, ax=ax)

ax.set_xlabel('Region')
ax.set_ylabel('Population')


ax.set_xticklabels(ax.get_xticklabels(), rotation=90, ha='right')
plt.tight_layout()
plt.show()


```
